homepage:
    path: /
    controller: App\Controller\DefaultController::index

table:
    path: /table
    controller: App\Controller\TableController::index

user:
    path: /user/{username}
    controller: App\Controller\UserController::index
